version: '3.8'
services:
  postgres:
    container_name: postgrescontainer
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      
    networks:
      - hasura-postgres-network
    ports:
      - "5432:5432"
    volumes:
      - "/c/Users/Juan/OneDrive/Documentos/ToDo-List-App/docker/volumes/postgres:/var/lib/postgresql/data"

  hasura:
    container_name: hasuracontainer
    image: hasura/graphql-engine
    restart: always
    depends_on:
      - postgres
    networks:
      - hasura-postgres-network
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:12345@postgres:5432/hasura_db
      HASURA_GRAPHQL_ADMIN_SECRET: 12345
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    volumes:
      - "/c/Users/Juan/OneDrive/Documentos/ToDo-List-App/docker/volumes/hasura:/hasura-data"
networks:
  hasura-postgres-network:
    driver: bridge